

SELECT * FROM test;

INSERT INTO test(no,str) VALUES(1, 'user1');
commit;

CREATE TABLE replyTblhgs(
    RNO NUMBER NOT NULL,
    BNO NUMBER NOT NULL,
    REPLY VARCHAR2(1000 BYTE) NOT NULL,
    REPLYER VARCHAR2(50 BYTE) NOT NULL,
    REPLYDATE DATE,
    RUPDATEDATE DATE,
    CONSTRAINT REPLYTBL FOREIGN KEY(BNO) REFERENCES boardTblhgs(BNO),
    CONSTRAINT REPLYTBL_PK PRIMARY KEY(RNO)
);


CREATE TABLE boardTblhgs(
    BNO NUMBER NOT NULL,
    TITLE VARCHAR2(200 BYTE) NOT NULL,
    CONTENT VARCHAR2(2000 BYTE) NOT NULL,
    WRITER VARCHAR2(50 BYTE) NOT NULL,
    REGDATE DATE,
    UPDATEDATE DATE,
    CONSTRAINT BOARDTBL_PK PRIMARY KEY(BNO)
);

CREATE TABLE Notice(
    NO NUMBER NOT NULL,
    id VARCHAR2(30 BYTE) NOT NULL,
    title VARCHAR2(50 BYTE),
    content VARCHAR2(100),
    create_date TIMESTAMP,
    CONSTRAINT NOTICE_PK PRIMARY KEY(NO)
);
--시퀀스 생성
CREATE SEQUENCE auto_increment START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;
INSERT INTO notice(id, title, content, create_date) VALUES('JANE', 'title TEST', 'This is ...','2021-07-10 17:50:10');
-- TIMESTAMP 포맷 수정
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';
SELECT ROWNUM, notice.* FROM notice;



